api/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^play', views.game_loop, name='play'),
    url(r'^total-score', views.total_score, name='total_score'),
    url(r'^game', views.BowlingGameGameView.as_view(), name='game'),
    url(r'^model', views.BowlingGameModelView.as_view(), name='model'),
    url(r'^start', views.start_game, name='start_game')
]

bowling_game/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from bowling_game import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^', include('game.urls', namespace='game')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

game/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from game import views


urlpatterns = [
    url(r'^start', views.start_game, name='start'),
    url(r'^loop', views.game_loop, name='loop'),
    url(r'^play', views.initial_load, name='play'),
    url(r'^end', views.initial_load, name='end'),
    url(r'^', TemplateView.as_view(template_name="index.html")),
]

game/models.py
from django.db import models

# Create your models here.

class BowlingGame(models.Model):
    Frame = models.PositiveSmallIntegerField()
    FrameRow = models.PositiveSmallIntegerField()
    Result = models.PositiveSmallIntegerField(blank=True, null=True)
    StrikeSpare = models.PositiveSmallIntegerField(blank=True, null=True)
    StrikeSpareInfo = models.CharField(max_length=1, blank=True, null=True)
    Time = models.DateTimeField(blank=True, null=True)
    GameId = models.PositiveIntegerField()
    StateOfGame = models.PositiveSmallIntegerField(default=1)

    class Meta:
        ordering = ('GameId',)

    def __str__(self):
        return str(self.GameId)

game/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.db.models import Max
from django.db.models import Sum
from .models import BowlingGame
import datetime
import random

# Create your views here.


def start_game(request):
    a = BowlingGame.objects.all().aggregate(Max('GameId'))['GameId__max'] + 1 #Get ID for the game
    BowlingGame.objects.bulk_create(eval(open("game/constants/bulk_list.txt").read())) #Create the game frame. eval is just space saver
    return HttpResponseRedirect('/play/') #Redirect to the play rout. This method allows path only as argument


def initial_load(request): #This func is doing the frontend while the game is running except end page
    # vars needed for the render
    a = BowlingGame.objects.all().aggregate(Max('GameId'))['GameId__max']
    game_frame = BowlingGame.objects.filter(GameId=a)
    total = BowlingGame.objects.filter(GameId=a).aggregate(Sum('Result'))['Result__sum']
    exit = BowlingGame.objects.filter(GameId=a).aggregate(Max('StateOfGame'))['StateOfGame__max']

    d, m = {}, 1 #This is just to save few lines. It's good in combination with 'eval' but at the end I have just dict instead of query which is bad
    for x in range(1, 11):
        d["result_frame_{0}".format(x)] = BowlingGame.objects.filter(GameId=a, Frame=m).aggregate(Sum('Result'))['Result__sum']
        m += 1

    if exit == 1: #Check the status of the game and exit it when is 2. Consider bool
        return render(request, 'play.html', eval(open("game/constants/render_dict_play.txt").read()))
    else:
        # needed for the stats on the end page
        num_of_strikes = BowlingGame.objects.filter(GameId=a, StrikeSpareInfo='X').count()
        num_of_spares = BowlingGame.objects.filter(GameId=a, StrikeSpareInfo='/').count()
        num_of_rolls = 21 - BowlingGame.objects.filter(GameId=a, Time=None).count()
        time_first = BowlingGame.objects.filter(GameId=a, Time__lt=datetime.datetime.now()).order_by('Time').first().Time
        time_last = BowlingGame.objects.filter(GameId=a, Time__lt=datetime.datetime.now()).order_by('Time').last().Time
        time = time_last - time_first
        time = time.seconds
        best_frame_result = max(d.values())
        total_games = a
        return render(request, 'end.html', eval(open("game/constants/render_dict_end.txt").read()))


def game_loop(request): #This is my dispatch function
    a = BowlingGame.objects.all().aggregate(Max('GameId'))['GameId__max']
    first_roll = BowlingGame.objects.filter(GameId=a, Time=None).first()
    frame = first_roll.Frame
    roll = first_roll.FrameRow

    if frame == 1 and roll == 1:
        player_turn_one()
    elif frame == 10:
        player_turn_last()
    else:
        result_frame = BowlingGame.objects.filter(GameId=a, Frame=frame).aggregate(Sum('Result'))['Result__sum']
        if result_frame == None:
            player_turn_one()
        else:
            player_turn_two()
    return redirect('/play/') #Redirect by using different method. It allows arguments to be passed though I need to look at this closer


def first_frame(): #Return random result for the first roll
    return (random.randint(0, 10))


def second_frame(old_score): #And then for the second
    return (random.randint(0, 10 - old_score))


def player_turn_one(): #This is for the first roll of the frame
    a = BowlingGame.objects.all().aggregate(Max('GameId'))['GameId__max']
    frame = BowlingGame.objects.filter(GameId=a, Time=None).first().Frame
    score = first_frame()
    revisions = BowlingGame.objects.filter(GameId=a, StrikeSpare__gt=0)

    for i in revisions: #Revise the previous results
        i.Result += score
        i.StrikeSpare -= 1
        i.save()
    record = BowlingGame.objects.get(GameId=a, Frame=frame, FrameRow=1)
    record.Result = score
    record.Time = datetime.datetime.now()
    if score == 10: #Check for Strike
        record.StrikeSpare = 2
        record.StrikeSpareInfo = 'X'
        next_record = BowlingGame.objects.get(GameId=a, Frame=frame, FrameRow=2)
        next_record.Time = datetime.datetime.now()
        next_record.save()
    record.save()


def player_turn_two(): #This is the second roll
    a = BowlingGame.objects.all().aggregate(Max('GameId'))['GameId__max']
    frame = BowlingGame.objects.filter(GameId=a, Time=None).first().Frame
    old_score = BowlingGame.objects.get(GameId=a, Frame=frame, FrameRow=1).Result
    score = second_frame(old_score)
    revisions = BowlingGame.objects.filter(GameId=a, StrikeSpare__gt=0)

    for i in revisions: #Revisions of the result if any
        i.Result += score
        i.StrikeSpare -= 1
        i.save()
    record = BowlingGame.objects.get(GameId=a, Frame=frame, FrameRow=2)
    record.Result = score
    record.Time = datetime.datetime.now()
    total_for_frame = old_score + score
    if total_for_frame == 10: #Check for spare
        record.StrikeSpare = 1
        record.StrikeSpareInfo = '/'
        record.save()
    record.save()


def player_turn_last(): #This is for the last frame.
    a = BowlingGame.objects.all().aggregate(Max('GameId'))['GameId__max']
    first_roll = BowlingGame.objects.filter(GameId=a, Time=None).first()
    frame = first_roll.Frame
    roll = first_roll.FrameRow

    if roll == 1: #First roll
        score = first_frame()
        revisions = BowlingGame.objects.filter(GameId=a, StrikeSpare__gt=0)
        for i in revisions:
            i.Result += score
            i.StrikeSpare -= 1
            i.save()
        record = BowlingGame.objects.get(GameId=a, Frame=frame, FrameRow=1)
        record.Result = score
        record.Time = datetime.datetime.now()
        if score == 10:
            record.StrikeSpare = 2
            record.StrikeSpareInfo = 'X'
        record.save()
    if roll == 2: #Second Roll
        old_record = BowlingGame.objects.get(GameId=a, Frame=frame, FrameRow=1).Result
        if old_record == 10:
            score = first_frame()
            revisions = BowlingGame.objects.filter(GameId=a, StrikeSpare__gt=0)
            for i in revisions:
                i.Result += score
                i.StrikeSpare -= 1
                i.save()
            record = BowlingGame.objects.get(GameId=a, Frame=frame, FrameRow=2)
            record.Result = score
            record.Time = datetime.datetime.now()
            if score == 10:
                record.StrikeSpare = 1
                record.StrikeSpareInfo = 'X'
                record.save()
            record.save()
        if old_record < 10:
            old_score = old_record
            score = second_frame(old_score)
            revisions = BowlingGame.objects.filter(GameId=a, StrikeSpare__gt=0)
            for i in revisions:
                i.Result += score
                i.StrikeSpare -= 1
                i.save()
            record = BowlingGame.objects.get(GameId=a, Frame=frame, FrameRow=2)
            record.Result = score
            record.Time = datetime.datetime.now()
            total_for_frame = old_score + score
            if total_for_frame == 10:
                record.StrikeSpare = 1
                record.StrikeSpareInfo = '/'
                record.save()
            if total_for_frame < 10:
                record.StateOfGame = 2
                record.save()
    if roll == 3: #And last
        score = first_frame()
        revisions = BowlingGame.objects.filter(GameId=a, StrikeSpare__gt=0)
        for i in revisions:
            i.Result += score
            i.StrikeSpare -= 1
            i.save()
        record = BowlingGame.objects.get(GameId=a, Frame=frame, FrameRow=3)
        record.Result = score
        record.Time = datetime.datetime.now()
        record.StateOfGame = 2
        record.save()

game/templates/end.html
{% load staticfiles %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Bowling Game</title>

        <!-- Bootstrap core CSS -->
        <link href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.min.css' %}" rel="stylesheet">
        <!-- Custom styles for this template -->
        <link href="{% static 'bootstrap-3.3.7-dist/css/jumbotron-narrow.css' %}" rel="stylesheet">
        <!-- My Custom CSS -->
        <link href="{% static 'bootstrap-3.3.7-dist/css/custom.css' %}" rel="stylesheet">

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>

    <body>
      <div class="container">
        <table>
          <tr>
            <td colspan="2">Frame 1</td>
            <td colspan="2">Frame 2</td>
            <td colspan="2">Frame 3</td>
            <td colspan="2">Frame 4</td>
            <td colspan="2">Frame 5</td>
            <td colspan="2">Frame 6</td>
            <td colspan="2">Frame 7</td>
            <td colspan="2">Frame 8</td>
            <td colspan="2">Frame 9</td>
            <td colspan="3">Frame 10</td>
          </tr>

          <tr>
          {% for frame in game_frame %}
            <td>{{ frame.Result|default_if_none:"o" }}</td>
          {% endfor %}
          </tr>
          <tr>
            <td colspan="2">{{ result_frame_1|default_if_none:"o" }}</td>
            <td colspan="2">{{ result_frame_2|default_if_none:"o" }}</td>
            <td colspan="2">{{ result_frame_3|default_if_none:"o" }}</td>
            <td colspan="2">{{ result_frame_4|default_if_none:"o" }}</td>
            <td colspan="2">{{ result_frame_5|default_if_none:"o" }}</td>
            <td colspan="2">{{ result_frame_6|default_if_none:"o" }}</td>
            <td colspan="2">{{ result_frame_7|default_if_none:"o" }}</td>
            <td colspan="2">{{ result_frame_8|default_if_none:"o" }}</td>
            <td colspan="2">{{ result_frame_9|default_if_none:"o" }}</td>
            <td colspan="3">{{ result_frame_10|default_if_none:"o" }}</td>
          </tr>
          <tr>
          {% for frame in game_frame %}
            <td>{{ frame.StrikeSpareInfo|default_if_none:" " }}</td>
          {% endfor %}
          </tr>
          <tr>
            <td colspan="21">Your total score is: {{ total }}</td>
          </tr>

        </table>

    <div>1-10 - this is your score; 'X' means strake; '/' means spare; 'o' means you are still to roll</div>
    <h2 align="center">As you possibly expect you won!</h2>
    <h3 align="center">Pease look at some statistics about your current game:</h3>
    <h5 align="center">TOTAL SCORE: {{ total }}</h5>
    <h5 align="center">NUMBER OF STRIKES: {{ num_of_strikes|default_if_none:"0" }}</h5>
    <h5 align="center">NUMBER OF SPARES: {{ num_of_spares|default_if_none:"0" }}</h5>
    <h5 align="center">NUMBER OF ROLLS: {{ num_of_rolls|default_if_none:"0" }}</h5>
    <h5 align="center">TOTAL TIME FOR THE GAME: {{ time|default_if_none:"0" }}s</h5>
    <h5 align="center">BEST FRAME RESULT: {{ best_frame_result|default_if_none:"0" }}</h5>
    <h3 align="center">And some overall performance:</h3>
    <h5 align="center">TOTAL GAMES SO FAR: {{ total_games|default_if_none:"0" }}</h5>

        <form id="mycalc" action="{% url 'game:start' %}" style="padding-top:50px">
            <div class="col-md-12 text-center">
                <span><input class="btn btn-block btn-primary" type="submit" value="Start New Game"></span>
            </div>
        </form>


        <footer class="footer">
          <p style="padding-top:50px">&copy; 2017 Leno, Inc.</p>
        </footer>

        <script src="{% static 'bootstrap-3.3.7-dist/js/jquery-1.10.1.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'bootstrap-3.3.7-dist/js/js.cookie.js' %}" type="text/javascript"></script>
  </div>
</body>

</html>

game/templates/index.html
{% load staticfiles %}
{% load crispy_forms_tags %}
{{ form.валута_от.errors }}

<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Bowling Game</title>

        <!-- Bootstrap core CSS -->
        <link href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.min.css' %}" rel="stylesheet">
        <!-- Custom styles for this template -->
        <link href="{% static 'bootstrap-3.3.7-dist/css/jumbotron-narrow.css' %}" rel="stylesheet">
        <!-- My Custom CSS -->
        <link href="{% static 'bootstrap-3.3.7-dist/css/custom.css' %}" rel="stylesheet">

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>

    <body>
      <div class="container">
        <div class="header clearfix" align="center">
          <h2 class="text-muted" style="padding-bottom:60px">Bowling Game</h2>
        </div>

        <form id="mycalc" name="start_new_game" action="{% url 'game:start' %}" method="GET" style="padding-bottom:150px">
            <div class="col-md-12 text-center">
                {% csrf_token %}
                <span><input class="btn btn-block btn-primary" type="submit" value="Start New Game"></span>
            </div>
        </form>

        <footer class="footer">
          <p>&copy; 2017 Leno, Inc.</p>
        </footer>

        <script src="{% static 'bootstrap-3.3.7-dist/js/jquery-1.10.1.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'bootstrap-3.3.7-dist/js/js.cookie.js' %}" type="text/javascript"></script>

      </div>

    </body>

</html>

game/templates/play.html
{% load staticfiles %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Bowling Game</title>

        <!-- Bootstrap core CSS -->
        <link href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.min.css' %}" rel="stylesheet">
        <!-- Custom styles for this template -->
        <link href="{% static 'bootstrap-3.3.7-dist/css/jumbotron-narrow.css' %}" rel="stylesheet">
        <!-- My Custom CSS -->
        <link href="{% static 'bootstrap-3.3.7-dist/css/custom.css' %}" rel="stylesheet">

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>

    <body>
      <div class="container">
        <div class="header clearfix" align="center">
          <h2 class="text-muted" style="padding-bottom:60px">Bowling Game</h2>
        </div>


        <table>
          <tr>
            <td colspan="2">Frame 1</td>
            <td colspan="2">Frame 2</td>
            <td colspan="2">Frame 3</td>
            <td colspan="2">Frame 4</td>
            <td colspan="2">Frame 5</td>
            <td colspan="2">Frame 6</td>
            <td colspan="2">Frame 7</td>
            <td colspan="2">Frame 8</td>
            <td colspan="2">Frame 9</td>
            <td colspan="3">Frame 10</td>
          </tr>

          <tr>
          {% for frame in game_frame %}
            <td>{{ frame.Result|default_if_none:"o" }}</td>
          {% endfor %}
          </tr>

          <tr>
            <td colspan="2">{{ result_frame_1|default_if_none:"o" }}</td>
            <td colspan="2">{{ result_frame_2|default_if_none:"o" }}</td>
            <td colspan="2">{{ result_frame_3|default_if_none:"o" }}</td>
            <td colspan="2">{{ result_frame_4|default_if_none:"o" }}</td>
            <td colspan="2">{{ result_frame_5|default_if_none:"o" }}</td>
            <td colspan="2">{{ result_frame_6|default_if_none:"o" }}</td>
            <td colspan="2">{{ result_frame_7|default_if_none:"o" }}</td>
            <td colspan="2">{{ result_frame_8|default_if_none:"o" }}</td>
            <td colspan="2">{{ result_frame_9|default_if_none:"o" }}</td>
            <td colspan="3">{{ result_frame_10|default_if_none:"o" }}</td>
          </tr>
          <tr>
          {% for frame in game_frame %}
            <td height="38">{{ frame.StrikeSpareInfo|default_if_none:" " }}</td>
          {% endfor %}
          </tr>
          <tr>
            <td colspan="21">Your total score is: {{ total|default_if_none:"0" }}</td>
          </tr>

        </table>
      </div>
      <div>1-10 - this is your score, 'X' means strake, '/' means spare, 'o' means you are still to roll</div>
      <div>
        <form id="mybow" name="row_the_bow" action="{% url 'game:loop' %}" method="GET" style="padding-top:75px">
            <div class="col-md-12 text-center">
                {% csrf_token %}
                <span><input class="btn btn-block btn-primary" type="submit" value="Roll The Bow"></span>
            </div>
        </form>


        <footer class="footer">
          <p style="padding-top:50px">&copy; 2017 Leno, Inc.</p>
        </footer>

        <script src="{% static 'bootstrap-3.3.7-dist/js/jquery-1.10.1.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'bootstrap-3.3.7-dist/js/js.cookie.js' %}" type="text/javascript"></script>

      </div>

    </body>

</html>